### ISSUE TITLE
Decay of Inventory instance leads to negative contents

### ISSUE THREAD

**Issue by Cs137** [radioactivedecay/radioactivedecay#113]
#### What is the issue?

If one lets a certain inventory decay, the outcome contains negative amounts of certain isotopes (e.g. `Po-214` content in example underneath). This seems to be the case only for the decay of `Inventory` instances, but not for `InventoryHP` instances. The latter leads to a reasonable result.

#### Steps to reproduce

Input:
```
rd.inventory.Inventory({"U-238": 1.0}, units="g").decay(10, units="d")
```

Output:
```
Inventory activities (Bq): {np.str_('At-218'): np.float64(0.0), np.str_('Bi-210'): np.float64(0.0), np.str_('Bi-214'): np.float64(0.0), np.str_('Hg-206'): np.float64(-4.2152023643385645e-20), np.str_('Pa-234'): np.float64(4.798156412884903), np.str_('Pa-234m'): np.float64(3108.1707289918454), np.str_('Pb-206'): np.float64(-0.0), np.str_('Pb-210'): np.float64(2.0704246129354228e-12), np.str_('Pb-214'): np.float64(3.440971871547959e-12), np.str_('Po-210'): np.float64(0.0), np.str_('Po-214'): np.float64(-2.007288088775711e-12), np.str_('Po-218'): np.float64(0.0), np.str_('Ra-226'): np.float64(1.8385370562866557e-12), np.str_('Rn-218'): np.float64(2.875605407591459e-19), np.str_('Rn-222'): np.float64(4.28777803501668e-12), np.str_('Th-230'): np.float64(7.492684845997089e-12), np.str_('Th-234'): np.float64(3108.485222106795), np.str_('Tl-206'): np.float64(-7.852319832996412e-18), np.str_('Tl-210'): np.float64(0.0), np.str_('U-234'): np.float64(0.00012585495413693673), np.str_('U-238'): np.float64(12436.520353926655)}, decay dataset: icrp107_ame2020_nubase2020
```

#### Environment
OS version: `Linux version 6.12.1-arch1-1`
Python version: `3.12.7`
radioactivedecay version: `0.5.1`
Installed via: `pip`

**Comment by alexmalins** [comment]
Hey Christian - I think this is just unavoidable floating point round off errors / instabilities 
if it's important for you not to have the minus numbers, the solution is as you say to use `InventoryHP`

**Comment by alexmalins** [comment]
In fact I documented this exact problem already here: https://radioactivedecay.github.io/theory.html#notes-on-computation-and-numerical-precision
