### ISSUE TITLE
Issue#50 (Import failure with SymPy 1.9) back again as of SymPy-1.10. 

### ISSUE THREAD

**Issue by radioactivedecay-github** [radioactivedecay/radioactivedecay#67]
Looks like [this](https://github.com/radioactivedecay/radioactivedecay/issues/50) became an issue once again as of SymPy-1.10. The source of the problem is [this](https://github.com/radioactivedecay/radioactivedecay/blob/main/radioactivedecay/decaydata.py#L766) line in [decaydata.py](https://github.com/radioactivedecay/radioactivedecay/blob/main/radioactivedecay/decaydata.py):

```py
sympy_pickle_version = "1.9" if sympy.__version__ >= "1.9" else "1.8"
```

The check for version greater than or equal to "1.9" fails for "1.10" because:

```py
>>> "1.10" >= "1.9"
False
```

Here is a simple solution based on [this](https://stackoverflow.com/a/11887825) answer on SO. Replace the [following lines](https://github.com/radioactivedecay/radioactivedecay/blob/main/radioactivedecay/decaydata.py#L765-L766):

```py
    if load_sympy:
        sympy_pickle_version = "1.9" if sympy.__version__ >= "1.9" else "1.8"
```

with:

```py
      versiontuple = lambda v: tuple(map(int, (v.split("."))))                               
      if load_sympy:                                                                         
          sympy_pickle_version = "1.9" if versiontuple(sympy.__version__) >= versiontuple("1.9") else "1.8" 
```

_Originally posted by @radioactivedecay-github in https://github.com/radioactivedecay/radioactivedecay/issues/50#issuecomment-1067504317_

**Comment by alexmalins** [comment]
Hi @radioactivedecay-github, thanks for catching this!
PR #68 and release 0.4.10 fix this issue. Went with setuptools/pkg_resources for version string parsing in the end as they seemed a more robust solution after reading the stackoverflow thread comments.

**Comment by radioactivedecay-github** [comment]
@alexmalins Thanks for fixing this so quickly. Also, thank you for creating this package. Cheers!

**Comment by alexmalins** [comment]
@radioactivedecay-github No worries & thanks again. The traceback for this error was not so helpful, but your issue described the problem code and the solution perfectly.
