### ISSUE TITLE
disenigrations per minute

### ISSUE THREAD

**Issue by snuetzmann** [radioactivedecay/radioactivedecay#87]
#### What is the issue?

After creating an inventory and calling activities('dpm') I recieve the opposite of the correct answer.  1 Bq = 60 dpm , but the result is 1/60 instead

#### Steps to reproduce

Just make an inventory with inv = rd.Inventory({'H-3', 1.0})   inv.activites('dpm')  should return 60 but instead returns .01666

#### Environment
OS version: 
Python version: 
radioactivedecay version: 
Installed via: 

MacOs in VSCode
Python 3.9.6
radioactivedecay version 0.4.16

#### Additional context

Please email back to snuetzmann@attentionit.com

**Comment by alexmalins** [comment]
Hi @snuetzmann - thanks for this bug report 🙌 
I just released v0.4.17 which corrects the problem. You can download it from PyPI now, and it will be available from conda-forge in the next few hours.

**Comment by alexmalins** [comment]
BTW I hope it's ok, but I just edited your email address out of your message. This will hopefully protect against bots harvesting it then filling your inbox with spam 👌
